"""empty message

Revision ID: 282b3a23f660
Revises: 2fe682204984
Create Date: 2023-04-01 18:50:43.714792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282b3a23f660'
down_revision = '2fe682204984'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
