"""empty message

Revision ID: 2a0555849cff
Revises: dc2ca804fe27
Create Date: 2023-04-01 18:29:09.826657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0555849cff'
down_revision = 'dc2ca804fe27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
