"""empty message

Revision ID: 98b2b4655119
Revises: acf8c2909a3e
Create Date: 2023-04-01 20:21:36.139548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b2b4655119'
down_revision = 'acf8c2909a3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
