"""empty message

Revision ID: acf8c2909a3e
Revises: c8ccf1e78e52
Create Date: 2023-04-01 20:13:55.329922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf8c2909a3e'
down_revision = 'c8ccf1e78e52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ratings', 'cats', ['cat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    # ### end Alembic commands ###
