"""empty message

Revision ID: c8ccf1e78e52
Revises: f71a2ea6a1cd
Create Date: 2023-04-01 19:57:07.372861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ccf1e78e52'
down_revision = 'f71a2ea6a1cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
