"""empty message

Revision ID: dc2ca804fe27
Revises: fb80008f343f
Create Date: 2023-04-01 18:28:44.904336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2ca804fe27'
down_revision = 'fb80008f343f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
