"""empty message

Revision ID: f71a2ea6a1cd
Revises: 75ed974999fe
Create Date: 2023-04-01 19:12:24.326210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71a2ea6a1cd'
down_revision = '75ed974999fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
